options:
  celery_broker:
    type: string
    default: pyamqp://guest@localhost//
    description: Celery broker URL
  virtinfo_endpoint:
    type: string
    default: http://localhost:6543/githosting
    description: Virtinfo endpoint (Launchpad/Turnipcake)
  virtinfo_timeout:
    type: int
    default: 15
    description: Timeout for virtinfo requests, in seconds.
  prefetch_multiplier:
    type: int
    default: 1
    description: Celery prefetch multiplier for each worker.
  celery_queues:
    type: string
    default: repacks,celery
    description: Celery queues, comma-separated and enumerated without spaces.
