options:
  build_label:
    type: string
    default: ""
    description: Build label to run.
  nagios_context:
    default: "juju"
    type: string
    description: |
      Used by the nrpe-external-master subordinate charm.
      A string that will be prepended to instance name to set the host name
      in nagios. So for instance the hostname would be something like -
        juju-turnip-0
      If you're running multiple environments with the same services in them
      this allows you to differentiate between them.
  base_dir:
    type: string
    default: '/srv/turnip'
    description: Root checkout/srv directory.
  user:
    type: string
    default: turnip
    description: The service will run as this user.
  user_id:
    type: int
    default: 1002
    description: >
      The service user will be created with this ID.  Fixing this value
      ensures that a storage volume can be used consistently across multiple
      units.
  group:
    type: string
    default: turnip
    description: The service will run under this group.
  group_id:
    type: int
    default: 1002
    description: >
      The service group will be created with this ID.  Fixing this value
      ensures that a storage volume can be used consistently across multiple
      units.
  log_hosts_allow:
    type: string
    default: ""
    description: >
      Hosts that should be allowed to rsync logs. Note that this relies on
      basenode.
  swift_username:
    type: string
    default: ""
    description: Username to use when accessing Swift.
  swift_password:
    type: string
    default: ""
    description: Password to use when accessing Swift.
  swift_auth_url:
    type: string
    default: ""
    description: URL for authenticating against Keystone.
  swift_storage_url:
    type: string
    default: ""
    description: URL for fetching from Swift (for anonymous access).
  swift_region_name:
    type: string
    default: ""
    description: Swift region.
  swift_tenant_name:
    type: string
    default: ""
    description: Entity that owns resources.
  swift_container_name:
    type: string
    default: ""
    description: Container to put objects in.
  haproxy_service_options:
    type: string
    description: HAProxy service options.
    default: |
      - mode tcp
      - option tcplog
      - balance leastconn
  haproxy_server_options:
    type: string
    description: HAProxy server options.
    default: check
  # layer-apt
  install_sources:
    default: |
      - ppa:launchpad/ppa
  install_keys:
    default: |
      - null  # PPA keys securely added via Launchpad.
