options:
  port:
    type: int
    default: 19418
    description: Pack backend port.
  virtinfo_endpoint:
    type: string
    default: http://localhost:6543/githosting
    description: Virtinfo endpoint (Launchpad/Turnipcake)
  virtinfo_timeout:
    type: int
    default: 15
    description: Timeout for virtinfo requests, in seconds.
  statsd_host:
    type: string
    default: 127.0.0.1
    description: Host for Telegraf configured with the statsd input.
  statsd_port:
    type: int
    default: 8125
    description: Port for Telegraf configured with the statsd input.
  statsd_prefix:
    type: string
    default: turnip
    description: Prefix for statsd metrics.
  statsd_environment:
    type: string
    default: local
    description: 'env' label to set for statsd metrics.
